### ISSUE TITLE
Reference to barrel.git breaks build

### ISSUE THREAD

**Issue by radicand** [prisma/prisma-engines#1150]
My arm64 build pipeline started failing, and I identified it as caused by this commit: https://github.com/prisma/prisma-engines/commit/a25d3c320c457986fe1b343b25c7f9182d8072f7

By dropping the `.git` suffix from the new reference to barrel so it reads `barrel = {git = "https://github.com/prisma/barrel"...`, it resolves the build issue. I'm not a Rust expert, but I had to delete Cargo.lock and attempt rebuild before it started working again.

**Comment by yoshuawuyts** [comment]
@radicand Thanks for opening this issue! We're aware of the dependency issues with `barrel`; a few days ago something indeed went wrong during a merge, and we ended up having to force push a fix to master. As a result of that some branches would no longer build; probably because as you shared the `Cargo.lock` needed to be updated. In the case of my branches, I managed to fix my build issues by rebasing on master -- but I'm guessing rebuilding the `Cargo.lock` file like you did also would've done the trick.

I'm glad you managed to resolve this though; and we appreciate you taking your time to share this with the team!
