### ISSUE TITLE
Change default mapping of scalar type `String`

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1288]
We decided to change the default mapping of `String` on MySQL. It used to be `varchar(191)` and should be `longtext` from now on. This will necessitate forbidding the usage of `String @unique` on MySQL when no native type is used.

**Comment by tomhoule** [comment]
Note: this also makes `id String @id` impossible on MySQL. I agree it's the right thing to do with native types.

**Comment by tomhoule** [comment]
Related: https://github.com/prisma/migrate/issues/116

**Comment by mavilein** [comment]
The challenging part is to adapt the tests in the query engine.

**Comment by carmenberndt** [comment]
This also means `cuid()` and `uuid()` are only possible with the native types, since they are almost always used in combination with `@id`.

**Comment by mavilein** [comment]
related: https://github.com/prisma/prisma/issues/3948

**Comment by albertoperdomo** [comment]
Update: It was decided to keep the varchar(191) mapping for String on MySQL.
Reasoning:
* mapping to longtext is good for consistency with Postgres, but comes at the expense of not being able to index, add uniqueness constraints, use the type for primary keys, etc.
* on Postgres it makes sense to use text, because none of these limitations apply
* it seems easier for a user to find out that in order to store longer texts they need to use some native type notation than for a user to understand why a String cannot be `@unique` or used as `@id`.
* we think users don't expect to be able to store Strings of unlimited length in a String column within a database.
