### ISSUE TITLE
Apply `clippy` to `query-engine`

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1387]
In the engines meeting we decided that we would like to apply clippy rules going forward. This task needs to accomplish those things:
1. Run `clippy` on the component mentioned above.
2. Fix those warnings. If a suggested change is debatable please raise this in the next engines meeting. This will be our way of figuring out which rules we want to use.
3. Add `clippy` for this component to our CI build.

**Comment by yoshuawuyts** [comment]
The majority of lints were already applied as part of https://github.com/prisma/prisma-engines/pull/1210/files; the only remaining task is to integrate this as part of engineer.

**Comment by yoshuawuyts** [comment]
Okay, it seems that Clippy isn't too keen on only linting individual crates. The following command should in theory scope Clippy to only run on `query-engine`, but I think because it sees dependencies in the same mono-repo it also applies lints there.

```sh
$ cargo clippy -p query-engine
```

Therefore I think the way to go is to implement the conversions on all crates, and then do one final pass on `engineer` which enforces it for _all_ crates. There are not too many lints left to implement, so if we can tick these off in reasonable time that should be easy.

Going to go ahead and close this for now since there's nothing left on this issue to do, and file an issue to add clippy to `engineer`.
