### ISSUE TITLE
Migrate: catch soft reset errors in CLI

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma-engines#1646]
When a soft reset happened, and the database hasn't been completely cleaned, the subsequent `applyMigrations` can fail. We could catch it in the CLI and provide guidelines on cleaning up the database.

**Comment by Jolg42** [comment]
Notes:

We do not know if a soft reset happened
-> engines could tell CLI that


We do not know if the applyMigration failed because of the soft reset
-> could be a typo / user edit of SQL file

So the message would be king of:
The migration failed to apply, this could be caused by:
- the soft reset not deleting *something*
- a problem in the migration.sql file

**Comment by tomhoule** [comment]
Return whether the reset was soft in `reset` RPC output.

**Comment by tomhoule** [comment]
This is the error implemented in prisma-engines/1660: "The fallback method for database resets failed, meaning Migrate could not clean up the database entirely. Original error: {error_code}\n{inner_error}",

We can easily expand or change the message now. Please come forward if you have improvements in mind, but otherwise I thinke we can consider this issue done.

**Comment by Jolg42** [comment]
Looks good!

**Comment by Jolg42** [comment]
Looks like we could close this?
