### ISSUE TITLE
Referential Action can't be set on inline relation for one-to-one optional

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma-engines#2501]
## Overview

Consider this datamodel

```prisma
model User {
  id        Int    @id
  commentId Int
  comment   Comment? @relation(fields: [commentId], references: [id], onDelete: Cascade)
}

model Comment {
  id     Int   @id
  author User
}
```

The datamodel validator will throw the following error:

```
Error parsing attribute "@relation": The relation field `comment` on Model `User` must not specify the `onDelete` or `onUpdate` argument in the @relation attribute. You must only specify it on the opposite field `author` on model `Comment`.
```

Looking at the code, IIUC, RAs _are_ expected to be put on the "forward" side. However, in the case of one2one optional, it is always the required side that's defined as the "forward" side. This forces users to put their RAs on the `Comment.author` side in this case.

```prisma
model User {
  id        Int    @id
  commentId Int
  comment   Comment? @relation(fields: [commentId], references: [id])
}

model Comment {
  id     Int   @id
  author User @relation(onDelete: Cascade)
}
```

I find this confusing and wonder if this is expected. RAs on other types of relations are always put on the inlined side.

## Expected behavior

For the datamodel above to accept RAs on the inlined side of the `User.comment` relation

**Comment by tomhoule** [comment]
## Recap of what happenid in #2503 

We are adding a validation. That will make prisma schemas that were valid invalid.

The following schema is invalid according to the rules for relations in the PSL:

```graphql
model Boom {
  id         Int      @id
  occurrence DateTime
  bam        Bam
}

model Bam {
  id        Int      @id
  boomId    Int?
  boom      Boom? @relation(fields: [boomId], references: [id])
}
```

Due to a gap in our validation logic, this was accepted as a valid schema, but it does not mean what it appears to mean. 

- A one-to-one relation can only be required on one side because it’s impossible to enforce requiredness on both sides.
- For the same reason, the required side is always going to be the one carrying the foreign key, so it *has* to define `fields` and `references`. This is what we now validate properly.
- Until this fix, Prisma understood the schema above as a 1:1 relation, with `fields` and `references` defined on the `Boom.bam` side. The `fields` and `references` on `Bam.boom` were ignored, and, as per the reformatting logic, an invisible `bamId` scalar field was added on the `Boom` model. It became visible if you reformatted. Starting with this release, the schema isn’t valid, but the reformatting logic will still always add the new scalar field on `Boom`.
