### ISSUE TITLE
Query engine playground crashes

### ISSUE THREAD

**Issue by RobertCraigie** [prisma/prisma-engines#2633]
### Bug description

Starting the query engine playground (`query-engine --enable-playground`) with the schema below crashes.

![c7ba4cde53114c7f46fb3df028a9ffc4](https://user-images.githubusercontent.com/23125036/151298882-95b162ca-6193-4da4-a222-ee8ea24ee3b2.png)

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:tmp.db"
}

generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = -1
}

model NotifiesOnProducts {
  address String
  handle  String
  Notify  Notify  @relation(fields: [address], references: [address])
  Product Product @relation(fields: [handle], references: [handle])

  @@id([address, handle])
}

model Notify {
  address  String               @id()
  products NotifiesOnProducts[]
}

model Product {
  handle   String               @id()
  notifies NotifiesOnProducts[]
}
```

### How to reproduce

1. Run `export RUST_LOG=info`
2. Run `prisma-query-engine --datamodel-path schema.prisma --enable-playground`
3. Navigate to the playground in your browser
4. Page goes blank with errors logged in the console

### Expected behavior

No error should occur

**Comment by matthewmueller** [comment]
Hey @RobertCraigie, just curious why you're using the internal API?

**Comment by RobertCraigie** [comment]
@matthewmueller I need to use the internal API  for https://github.com/RobertCraigie/prisma-client-py

**Comment by Weakky** [comment]
Hey @RobertCraigie,

That's a known internal bug. What the playground tells you is that all graphql types should have a least one field. Unfortunately, in certain cases (eg: a model only has an id and relations), it happens that we generate empty graphql types, which is not graphql compliant.

Since the playground is merely an internal tool that helps us test the engine, we won't fix that.

The workaround to this problem is to add a dummy optional field on the `NotifiesOnProducts` model (and perhaps the other ones) if you keep having an error. (eg: `tmp String?`)

Thanks for reporting nonetheless 🙏
