### ISSUE TITLE
Time zone problem

### ISSUE THREAD

**Issue by tingfeng-key** [prisma/prisma-engines#3272]
I want to know whether the time zone problem is an engine problem?
[Improve Timezone Support for Existing MySQL Databases configured with a Non-UTC Timezone](https://github.com/prisma/prisma/issues/5051)
[Add time zone conversion for timestamps](https://github.com/prisma/prisma/issues/3292)
[Timezone support](https://github.com/Brendonovich/prisma-client-rust/issues/154)

**Comment by janpio** [comment]
It is a universal problem in the current design and implementation. Some early assumption both around JS's `Date` (which we use as the data type in Prisma Client) and how we treat those values in our code (both TS and Rust, so the engines) turend out to be limiting in what we can achieve - leading to the issues you linked to. We will need to fully take this apart, understand all the use cases, and put it back together in a way that can support all of these.

If you use case is different from the ones already mentioned in the issues, please add a comment on them. Thanks.

**Comment by zhujinxuan** [comment]
Sorry for troubling a closed issue. I am thinking about adding 'timezone' attribute to datasource and change query-engine and schema-engine accordingly. If I make a PR like that, would you mind reviewing the PR if I finish it?

On the TS side, I don't think it would be a problem because nodeJS and browser only have one timezone by default.
