### ISSUE TITLE
Optimized Postgres Introspection

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#515]
We already greatly optimized the performance of the MySQL Introspection, but Postgres is still comparably slow: It takes ~30 seconds for the `discourse` database for example.

**Comment by tomhoule** [comment]
Open PR: https://github.com/prisma/prisma-engines/pull/517

I observed massive performance gains from these changes. On my machine, introspecting the same `discourse` database went from ~30 seconds to ~1 second. The general approach is the same as the optimization we did for mysql: instead of sending _n_ queries per table, do _n_ queries for the whole database, and return results in a map from table name to introspected structs, then build the tables from that.
