### ISSUE TITLE
Examine our implementation of CUIDs

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#881]
## Context
We maintain a fork of the cuid implementation for Rust: https://github.com/prisma/cuid-rust

We thought that CUIDs always have the length 25. We recently learned that our implementation instead generates CUIDs of a varying length. When generating 1.000.000 of them in a loop i got the following distribution:
- length 25: 10.000
- length 26: 90.000
- length 27: 900.000

I ran the same test for our [Java implementation](https://github.com/prisma/cuid-java) and all ids had a consistent length of 25.

This [comment](https://github.com/ericelliott/cuid/issues/164#issuecomment-516637547) of the original author of CUID suggests that a fluctuating length is normal.

## Goals
- understand whether this happens for the original JS implementation as well
- We want to understand where this fluctuation comes from. This should be done by comparing the implementations for JS, Java and Rust.

**Comment by matthewmueller** [comment]
- From my work side: I don't need anymore information. Work is happening here: https://github.com/prisma/upgrade/pull/44

- From my curiosity side: I'd like to know why the Java implementation differs
- From my double-check side: I'd like to make sure our Rust implementation follows the spec so we don't run into this problem again.

**Comment by yoshuawuyts** [comment]
Talked with @matthewmueller and we agreed to close this issue (:

**Comment by mplanchard** [comment]
Author of the forked Rust implementation here. Just happened to be digging around on this recently, found this issue, and wanted to add some context in case anyone else stumbles in.

Originally there was a minor discrepancy in the rust implementation in how the counter was being padded, leading to the variable lengths y'all saw. That was fixed in mplanchard/cuid-rust#2 and released with version 1.0.1, just in case you still need to pull it in.

Although the CUID author suggests that variable lengths are possible, as far as I can tell they are generally not going to happen in practice, at least not for a while. As the timestamp gets larger, the base 36 representation will take up more characters. It looks like it'll roll up form 8 to 9 characters sometime in 2059 or so. The slugs are always 10 characters and will remain so unless something changes, both in the original implementation and the rust one, despite docs in the original implementation that suggest they may be from 7 to 10 characters.

**Comment by janpio** [comment]
Thanks for the update @mplanchard. Are you effectively saying that we should look into replacing our custom fork with an up to date version of your repository/crate again as you think the problems we had are fixed?

**Comment by mplanchard** [comment]
Worth a shot! In addition to fixing the length issue, I made some pretty
nice performance improvements in 1.0.2. I’m also happy to accept PRs if
there are other fixes that y’all have made that you’d like to upstream. If
you don’t want to depend on it in directly, you may at least want to pull
in the changes from upstream.
