### ISSUE TITLE
Add tests using Cockroach DB 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#900]
Cockroach DB indicates it is wire protocol compatible with PostgreSQL: https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html

As some users see this as an indicator it can also be used with Prisma, we should test this and document our result in the documentation.

This would include adding a dockerized version of this database to our test matrix.

**Comment by yoshuawuyts** [comment]
Triage: the target outcome here is to find out whether it passes our test suite.

**Comment by yoshuawuyts** [comment]
First PR: https://github.com/prisma/engineer/pull/16

**Comment by vy-ton** [comment]
Hi, product manager at Cockroach Labs here. Let me know if any issues come up for your testing of if there's anything we can help answer during testing.

**Comment by yoshuawuyts** [comment]
One small snag we've hit with Cockroach: while the wire format is compatible with Postgres, the storage format may diverge. One example is the column IDs: I couldn't my local PgAdmin instance and thought it might just be a blip, but TypeORM notes that all numbers are actually encoded as strings ([src](https://typeorm.io/#/entities/column-types-for-cockroachdb)).

This means that while supporting CockroachDB is not a _lot_ of work since we're already wire compatible, we'll need to make adjustments on our side to be fully compatible, which means we'll have to make this an actual project.

@vy-ton is what I've said so far correct?

**Comment by yoshuawuyts** [comment]
Got the tests to run in CI and they failed; it seems pretty clear there are implementation differences between Postgres and Cockroach. This means it's up to Product to decide if and when we would want to support Cockroach.

**Comment by janpio** [comment]
Thanks.

Also surfaced at https://github.com/prisma/prisma/issues/2523#issuecomment-696746162

**Comment by rafiss** [comment]
@yoshuawuyts @janpio I'm an engineer at Cockroach Labs. Thanks for getting the tests set up!

> Got the tests to run in CI and they failed; it seems pretty clear there are implementation differences between Postgres and Cockroach. 

Could you copy/paste the failures here or link to them? That way we could try to estimate how much work would be involved.

> One example is the column IDs: I couldn't my local PgAdmin instance and thought it might just be a blip,

Could you describe what happened when you tried using PgAdmin?

> TypeORM notes that all numbers are actually encoded as strings

This is not actually true. I think that documentation you linked to is actually referring to the fact that TypeORM turns numbers into strings, see [the CockroachDB dialect in TypeORM](https://github.com/typeorm/typeorm/blob/b55a417ea4852ad2e66091cfa800534f7ccdd3c9/src/driver/cockroachdb/CockroachDriver.ts#L341). I believe they did this because CockroachDB by default uses 8 bytes to store "INT" columns and this causes some overflow issues for Javascript. (If a different integer size is required, that can be specified by using INT8 or INT4 types, or by using the `default_int_size` setting.)

**Comment by yoshuawuyts** [comment]
@rafiss thanks so much for popping by!

> Could you describe what happened when you tried using PgAdmin?

This may very well have been a configuration issue on my side since I installed PgAdmin just for this. But I got various warnings string warnings that seemed to originate from Python -- and while PgAdmin was able to see which databases existed, it had trouble reading out any other information on the databases. A quick search also surfaced that I wasn't the first one to experience this.

---

> This is not actually true. I think that documentation you linked to is actually referring to the fact that TypeORM turns numbers into strings, see the CockroachDB dialect in TypeORM. 

Ah, my bad -- I misread. I think after having seen the string parsing errors in PgAdmin I figured TypeORM might be referring to the same thing. Turns out they were unrelated 😅 

---

> Could you copy/paste the failures here or link to them? That way we could try to estimate how much work would be involved.

We've been talking about this with the team internally, and from the looks of it the bulk of the work would be in our translation layer. I'm not particularly well versed in that part of our codebase though, so that's about the extent of my knowledge there heh.

We've encountered several errors in CI; the two most common ones being:

```txt
Error querying the database: Error querying the database: db error: ERROR: at or near "if": syntax error: unimplemented: this syntax
```
```txt
ERROR: unimplemented: new schemas are unsupported
```
I believe this indicated we're not making it past the table initialization phase, which means there may be a longer tail of compatibility work needed beyond this.

**Comment by rafiss** [comment]
Of course, I'm very happy to help!

> while PgAdmin was able to see which databases existed, it had trouble reading out any other information on the databases. A quick search also surfaced that I wasn't the first one to experience this.

Ahh, got it. I do believe there are other compatibility issues with PgAdmin. One thing I'd mention -- if you were just looking for _any_ GUI and not PgAdmin specifically, perhaps you could try the [built-in CockroachDB Admin UI](https://www.cockroachlabs.com/docs/v20.2/admin-ui-overview.html).

> We've been talking about this with the team internally, and from the looks of it the bulk of the work would be in our translation layer. I'm not particularly well versed in that part of our codebase though, so that's about the extent of my knowledge there heh.

Not a problem! I am just interested in staying on top of which issues came up, since that also might help us prioritize work internally. 

As for the two errors that you pasted:

> Error querying the database: Error querying the database: db error: ERROR: at or near "if": syntax error: unimplemented: this syntax

Interesting.. I wonder if you could find the full query associated with that?

> ERROR: unimplemented: new schemas are unsupported

Good news here! Our next release (20.2) which should be generally available within a couple months has added support for this. If you're wiling to give it a shot, you can try out the tests with our [v20.2.0-beta.1](https://www.cockroachlabs.com/docs/releases/v20.2.0-beta.1). It's possible that the first error would be addressed as well, since the new version adds support for `IF NOT EXISTS` syntax in some places.

**Comment by rafiss** [comment]
@yoshuawuyts  Of course, I'm very happy to help!

> while PgAdmin was able to see which databases existed, it had trouble reading out any other information on the databases. A quick search also surfaced that I wasn't the first one to experience this.

Ahh, got it. I do believe there are other compatibility issues with PgAdmin. One thing I'd mention -- if you were just looking for _any_ GUI and not PgAdmin specifically, perhaps you could try the [built-in CockroachDB Admin UI](https://www.cockroachlabs.com/docs/v20.2/admin-ui-overview.html).

> We've been talking about this with the team internally, and from the looks of it the bulk of the work would be in our translation layer. I'm not particularly well versed in that part of our codebase though, so that's about the extent of my knowledge there heh.

Not a problem! I am just interested in staying on top of which issues came up, since that also might help us prioritize work internally. 

As for the two errors that you pasted:

> Error querying the database: Error querying the database: db error: ERROR: at or near "if": syntax error: unimplemented: this syntax

Interesting.. I wonder if you could find the full query associated with that?

> ERROR: unimplemented: new schemas are unsupported

Good news here! Our next release (20.2) which should be generally available within a couple months has added support for this. If you're wiling to give it a shot, you can try out the tests with our [v20.2.0-beta.1](https://www.cockroachlabs.com/docs/releases/v20.2.0-beta.1). It's possible that the first error would be addressed as well, since the new version adds support for `IF NOT EXISTS` syntax in some places.

**Comment by vy-ton** [comment]
@yoshuawuyts @janpio Can we set up a call between CockroachDB engineers and the Prisma team that works on database connectors? 

As @rafiss mentioned, we would like to prioritize work that would unblock our users from using Prisma with CockroachDB.

**Comment by thebiglabasky** [comment]
Hi @vy-ton,
We're unfortunately short on capacity right now as there's quite some work happening on supporting MSSQL.
Could we get back in touch once the horizon clears?

**Comment by vy-ton** [comment]
@thebiglabasky Yes, please reach back out when your roadmap opens up. Thank you for your reply!
