### ISSUE TITLE
Validate that there is only one @default(autoincrement()) per table, on an indexed column on MySQL

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma-engines#903]
It seems that this is not supported. This behaviour should be confirmed. If it is the case, we should probably incorporate this into schema validation.

**Comment by tomhoule** [comment]
This is the same issue as https://github.com/prisma/prisma/issues/1938

**Comment by do4gr** [comment]
- Sqlite -> auto_increment is only allowed on `Integer Primary Key`
- MySQL -> you can have one auto_increment column, it does not have to be the primary, but needs to be indexed 
- SqlServer -> only one auto_increment column is allowed per table
-Oracle -> only seems to support one auto_increment column as well
- Postgres -> you can have multiple auto_increment columns

For some of these it is possible to define sequences and assign default values based on seq.next() instead of using auto_increment / identity columns.

**Comment by tomhoule** [comment]
Now that @do4gr has researched this, I think we can bake this knowledge into schema validation. Candidating this for the next iteration as a schema parser issue.

**Comment by mavilein** [comment]
@tomhoule : Can you update the issue title accordingly then?
